name: AutoSneak
main: me.mannil.autosneak.AutoSneak
version: 1.7.2
softdepend: [AntiCheat]
website: http://plugin.evo-network.de/
author: SquallSeeD31, manniL
commands:
  sneak:
    description: Toggle sneaking on or off.
    usage: /sneak [on|off] - Toggles (or sets) sneak status.
permissions:
  autosneak.sneak:
    default: false
  autosneak.auto:
    default: false
  autosneak.exempt:
    default: op